// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mn4-nLJk69UjEqatuycsleLHZ2ToLMI',
    appId: '1:457327335761:web:9e654b089a9c132a039b70',
    messagingSenderId: '457327335761',
    projectId: 'login-da112',
    authDomain: 'login-da112.firebaseapp.com',
    storageBucket: 'login-da112.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjsgDOI83S3yGzSWk385KFXNZe6zEGsvU',
    appId: '1:457327335761:android:9df1a220258dc1ff039b70',
    messagingSenderId: '457327335761',
    projectId: 'login-da112',
    storageBucket: 'login-da112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARD8JqraYFUAWP-az9hG08vzQAcWqwjhM',
    appId: '1:457327335761:ios:8fc056d8b4f6d029039b70',
    messagingSenderId: '457327335761',
    projectId: 'login-da112',
    storageBucket: 'login-da112.appspot.com',
    iosClientId: '457327335761-1422h1tiqrlaiq379gtr1nrmi2h1qn2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARD8JqraYFUAWP-az9hG08vzQAcWqwjhM',
    appId: '1:457327335761:ios:f64e2a8c899a0990039b70',
    messagingSenderId: '457327335761',
    projectId: 'login-da112',
    storageBucket: 'login-da112.appspot.com',
    iosClientId: '457327335761-8uafmkomnquj1bvphqivn2gj0akj624b.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
